### ISSUE TITLE
NotADirectoryError

### ISSUE THREAD

**Issue by robintw** [Damnever/pigar#1]
pigar sounds great, and I've just tried to use it on my machine, but I get the following error:

```
Traceback (most recent call last):
  File "/opt/anaconda3/bin/pigar", line 7, in <module>
    from pigar.__main__ import main
  File "/opt/anaconda3/lib/python3.4/site-packages/pigar/__main__.py", line 17, in <module>
    _installed_pkgs = get_installed_pkgs_detail()
  File "/opt/anaconda3/lib/python3.4/site-packages/pigar/reqs.py", line 186, in get_installed_pkgs_detail
    for file in os.listdir(search_path):
NotADirectoryError: [Errno 20] Not a directory: '/opt/anaconda3/lib/python3.4/site-packages/setuptools-18.1-py3.4.egg'
```

I'm running Anaconda on OS X Yosemite, and I think it's having problems with dealing with `.egg` files.

Any ideas?

**Comment by Damnever** [comment]
Could you post your `sys.path`?

```python -c "import sys; print(sys.path)"```

**Comment by robintw** [comment]
Here it is:

```
['', '/Users/robin/code/6SV1.0B_NewSubroutines/src/facebook-sdk', '/opt/anaconda3/lib/python34.zip', '/opt/anaconda3/lib/python3.4', '/opt/anaconda3/lib/python3.4/plat-darwin', '/opt/anaconda3/lib/python3.4/lib-dynload', '/opt/anaconda3/lib/python3.4/site-packages', '/opt/anaconda3/lib/python3.4/site-packages/Sphinx-1.3.1-py3.4.egg', '/opt/anaconda3/lib/python3.4/site-packages/aeosa', '/opt/anaconda3/lib/python3.4/site-packages/setuptools-18.1-py3.4.egg']
```

Interestingly, it looks slightly weird...but I think .eggs are allowed to be on the path.

**Comment by Damnever** [comment]
Now, try to update it:

```pip install pigar --upgrade```

**Comment by robintw** [comment]
I now get the same error, but for a different file:

```
Traceback (most recent call last):
  File "/opt/anaconda3/bin/pigar", line 7, in <module>
    from pigar.__main__ import main
  File "/opt/anaconda3/lib/python3.4/site-packages/pigar/__main__.py", line 17, in <module>
    _installed_pkgs = get_installed_pkgs_detail()
  File "/opt/anaconda3/lib/python3.4/site-packages/pigar/reqs.py", line 193, in get_installed_pkgs_detail
    with open(top_level, 'r') as f:
NotADirectoryError: [Errno 20] Not a directory: '/opt/anaconda3/lib/python3.4/site-packages/abstract_rendering-0.5.1-py3.4.egg-info/top_level.txt'
```

**Comment by Damnever** [comment]
Try this:
```pip install git+https://github.com/Damnever/pigar.git@dir_error --upgrade```

**Comment by robintw** [comment]
Great, that works - thanks!

(and, now I've been able to test it, it's a great tool - thanks. I'll probably blog about it soon)
