### ISSUE TITLE
Python Installer: FileExistsError

### ISSUE THREAD

**Issue by yochananmarqos** [damnever/pigar#195]
**Describe the bug**

[AUR](https://aur.archlinux.org/packages/pigar) package maintainer here. 

When attempting to update to v2.1.2, Build successfully creates the wheel, however Installer fails. 

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.11/site-packages/installer/__main__.py", line 98, in <module>
    _main(sys.argv[1:], "python -m installer")
  File "/usr/lib/python3.11/site-packages/installer/__main__.py", line 94, in _main
    installer.install(source, destination, {})
  File "/usr/lib/python3.11/site-packages/installer/_core.py", line 87, in install
    record = destination.write_script(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/installer/destinations.py", line 230, in write_script
    entry = self.write_to_fs(
            ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/installer/destinations.py", line 167, in write_to_fs
    raise FileExistsError(message)
FileExistsError: File already exists: /build/pigar/pkg/pigar/usr/bin/pigar
```

**To Reproduce**
* Bump the pkgver and attempt to build the AUR package

**Context (Environment)**
 - OS: Manjaro Linux
 - Version of `Python`: 3.11.7
 - Version of `pigar`: 2.1.2

**Comment by damnever** [comment]
The version v2.1.3 has been released.
