### ISSUE TITLE
ImportError: No module named 'pigar.extractor'

### ISSUE THREAD

**Issue by paternal** [Damnever/pigar#25]
~~~sh
$ pip install git+https://github.com/Damnever/pigar.git@master --upgrade
...
$ pigar
Traceback (most recent call last):
  File "/home/louis/.virtualenvs/pypimonitor/bin/pigar", line 9, in <module>
    load_entry_point('pigar==0.6.8', 'console_scripts', 'pigar')()
  File "/home/louis/.virtualenvs/pypimonitor/lib/python3.5/site-packages/pkg_resources/__init__.py", line 568, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/louis/.virtualenvs/pypimonitor/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/home/louis/.virtualenvs/pypimonitor/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/home/louis/.virtualenvs/pypimonitor/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/louis/.virtualenvs/pypimonitor/lib/python3.5/site-packages/pigar/__main__.py", line 12, in <module>
    from .pypi import update_db, check_latest_version, search_names
  File "/home/louis/.virtualenvs/pypimonitor/lib/python3.5/site-packages/pigar/pypi.py", line 19, in <module>
    from .extractor import Extractor
ImportError: No module named 'pigar.extractor'
$ python --version
Python 3.5.1+
~~~

I can provide more information on request.
Regards

**Comment by Damnever** [comment]
OK, fixed.

**Comment by paternal** [comment]
Fixed. Thanks.
