### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by buriy** [Damnever/pigar#3]
# python 2.7
$ pigar
Traceback (most recent call last):
  File "/usr/local/bin/pigar", line 9, in <module>
    load_entry_point('pigar==0.5.4', 'console_scripts', 'pigar')()
  File "/usr/local/lib/python2.7/dist-packages/pigar/__main__.py", line 32, in main
    generate_reqs(save_path, project_path)
  File "/usr/local/lib/python2.7/dist-packages/pigar/__main__.py", line 93, in generate_reqs
    reqs, guess = extract_reqs(project_path)
  File "/usr/local/lib/python2.7/dist-packages/pigar/__main__.py", line 135, in extract_reqs
    modules, local_mods = project_import_modules(path)
  File "/usr/local/lib/python2.7/dist-packages/pigar/reqs.py", line 38, in project_import_modules
    modules.extend(file_import_modules(f.read()))
  File "/usr/local/lib/python2.7/dist-packages/pigar/reqs.py", line 56, in file_import_modules
    return list(_recursion(ic, data))
  File "/usr/local/lib/python2.7/dist-packages/pigar/reqs.py", line 49, in _recursion
    parsed = ast.parse(str_code)
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1306
    print("...", end=' ')
                    ^
SyntaxError: invalid syntax

**Comment by Damnever** [comment]
```
pip install git+https://github.com/Damnever/pigar.git@invalid_syntax --upgrade
```

**Comment by Damnever** [comment]
Some code like this:
```
exec "testing print_exception() -- <I>italics?</I>"
```
So I just ignore it...
