### ISSUE TITLE
Invalid syntax (another error)

### ISSUE THREAD

**Issue by buriy** [Damnever/pigar#4]
(also python 2.7)
$ pigar
Traceback (most recent call last):
  File "/usr/local/bin/pigar", line 9, in <module>
    load_entry_point('pigar==0.5.4', 'console_scripts', 'pigar')()
  File "/usr/local/lib/python2.7/dist-packages/pigar/__main__.py", line 32, in main
    generate_reqs(save_path, project_path)
  File "/usr/local/lib/python2.7/dist-packages/pigar/__main__.py", line 93, in generate_reqs
    reqs, guess = extract_reqs(project_path)
  File "/usr/local/lib/python2.7/dist-packages/pigar/__main__.py", line 135, in extract_reqs
    modules, local_mods = project_import_modules(path)
  File "/usr/local/lib/python2.7/dist-packages/pigar/reqs.py", line 38, in project_import_modules
    modules.extend(file_import_modules(f.read()))
  File "/usr/local/lib/python2.7/dist-packages/pigar/reqs.py", line 56, in file_import_modules
    return list(_recursion(ic, data))
  File "/usr/local/lib/python2.7/dist-packages/pigar/reqs.py", line 50, in _recursion
    ic.visit(parsed)
  File "/usr/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/lib/python2.7/ast.py", line 249, in generic_visit
    self.visit(item)
  File "/usr/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/lib/python2.7/ast.py", line 249, in generic_visit
    self.visit(item)
  File "/usr/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/lib/python2.7/ast.py", line 249, in generic_visit
    self.visit(item)
  File "/usr/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/local/lib/python2.7/dist-packages/pigar/reqs.py", line 104, in visit_FunctionDef
    self.visit(_node)
  File "/usr/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/lib/python2.7/ast.py", line 249, in generic_visit
    self.visit(item)
  File "/usr/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/local/lib/python2.7/dist-packages/pigar/reqs.py", line 79, in visit_Exec
    self._str_codes.add(node.body.s)
AttributeError: 'Name' object has no attribute 's'

**Comment by Damnever** [comment]
```
pip install git+https://github.com/Damnever/pigar.git@invalid_syntax --upgrade
```

**Comment by buriy** [comment]
Thanks, it helped for #3 and this one.
