### ISSUE TITLE
Searching names doesn't work in my environment

### ISSUE THREAD

**Issue by gh640** [damnever/pigar#41]
Thank you for this helpful package. 

I tried `pigar` command after installing it with `pip`, I got the following error.

```bash
$ pigar -s bs4
Starting search names ...
Traceback (most recent call last):
  File "/path/to/virtualenv/dir/bin/pigar", line 11, in <module>
    sys.exit(main())
  File "/path/to/virtualenv/dir/lib/python3.6/site-packages/pigar/__main__.py", line 261, in main
    Main()
  File "/path/to/virtualenv/dir/lib/python3.6/site-packages/pigar/__main__.py", line 33, in __init__
    self.search_package_by_name(names)
  File "/path/to/virtualenv/dir/lib/python3.6/site-packages/pigar/__main__.py", line 51, in search_package_by_name
    found, not_found = search_names(names, self.installed_pkgs)
  File "/path/to/virtualenv/dir/lib/python3.6/site-packages/pigar/pypi.py", line 46, in search_names
    version = extract_pkg_version(row.package)
  File "/path/to/virtualenv/dir/lib/python3.6/site-packages/pigar/pypi.py", line 115, in extract_pkg_version
    data = _pkg_json_info(pkg_name)
  File "/path/to/virtualenv/dir/lib/python3.6/site-packages/pigar/pypi.py", line 129, in _pkg_json_info
    data = json.loads(data.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

My environment is as the following:

```bash
$ pip freeze
...
pigar==0.7.1
...
```

```bash
$ python -V
Python 3.6.5
```

```bash
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G20015
```

To debug, I tried the following change and it started working.

```diff
--- a/pigar/pypi.py
+++ b/pigar/pypi.py
@@ -145,8 +145,9 @@ def download(url, headers=_HEADERS):
     """Download data from url."""
     f = None
     try:
+        import gzip
         f = urlopen(Request(url, headers=headers))
-        data = f.read()
+        data = gzip.decompress(f.read())
     finally:
         if f:
             f.close()
```

Or, removing the key `'Accept-Encoding'` in `pypi._HEADERS` also worked.

Does this occur only in my environment? Or, the new pypi.org changed response encoding?

I'm willing to share my settings and please let me know if I miss anything important to report an issue. Thank you in advance :)

**Comment by damnever** [comment]
Thank you for report it.

**Comment by damnever** [comment]
Please update to the latest version(0.7.2).

**Comment by gh640** [comment]
@damnever I tested the version 0.7.2 and it works perfectly! Thanks :)
