### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by XuCcc** [damnever/pigar#46]
version
- pigar 0.9.0
- python 2.7.3
- os windows7

```sh
Starting generate requirements ...
Traceback (most recent call last):
  File "/usr/local/bin/pigar", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pigar/__main__.py", line 261, in main
    Main()
  File "/usr/local/lib/python2.7/dist-packages/pigar/__main__.py", line 35, in __init__
    self.generate_reqs(save_path, project_path, ignores)
  File "/usr/local/lib/python2.7/dist-packages/pigar/__main__.py", line 102, in generate_reqs
    gr.generate_reqs()
  File "/usr/local/lib/python2.7/dist-packages/pigar/__main__.py", line 119, in generate_reqs
    reqs, try_imports, guess = self.extract_reqs()
  File "/usr/local/lib/python2.7/dist-packages/pigar/__main__.py", line 172, in extract_reqs
    self._project_path, self._ignores)
  File "/usr/local/lib/python2.7/dist-packages/pigar/reqs.py", line 60, in project_import_modules
    fmodules, try_ipts = file_import_modules(fake_path, f.read())
  File "/usr/local/lib/python2.7/dist-packages/pigar/reqs.py", line 79, in file_import_modules
    ic.visit(parsed)
  File "/usr/local/lib/python2.7/dist-packages/pigar/reqs.py", line 220, in visit
    getattr(self, method, lambda x: x)(node)
  File "/usr/local/lib/python2.7/dist-packages/pigar/reqs.py", line 153, in visit_Exec
    (node.body.elts[0].s, node.lineno + self._lineno))
AttributeError: 'Name' object has no attribute 's'
```

**Comment by damnever** [comment]
`python --version`?

Could you provide the minimal environment to reproduce it?

**Comment by damnever** [comment]
Can't reproduce it with Python 2.7.3, but https://github.com/damnever/pigar/commit/ee75dbca00b3af9c6fec089a8520076d0d86316e is the dirty fix.
