### ISSUE TITLE
For larger projects we get "maximum recursion depth exceeded"

### ISSUE THREAD

**Issue by buriy** [Damnever/pigar#5]
$ pigar
Exception RuntimeError: RuntimeError('maximum recursion depth exceeded',) in <generator object iter_fields at 0x7efe3bfd6640> ignored
Traceback (most recent call last):
  File "/usr/local/bin/pigar", line 9, in <module>
    load_entry_point('pigar==0.5.4', 'console_scripts', 'pigar')()
  File "/usr/local/lib/python2.7/dist-packages/pigar/__main__.py", line 32, in main
    generate_reqs(save_path, project_path)
  File "/usr/local/lib/python2.7/dist-packages/pigar/__main__.py", line 93, in generate_reqs
    reqs, guess = extract_reqs(project_path)
  File "/usr/local/lib/python2.7/dist-packages/pigar/__main__.py", line 136, in extract_reqs
    modules, local_mods = project_import_modules(path)
  File "/usr/local/lib/python2.7/dist-packages/pigar/reqs.py", line 38, in project_import_modules
    modules.extend(file_import_modules(f.read()))
  File "/usr/local/lib/python2.7/dist-packages/pigar/reqs.py", line 60, in file_import_modules
    return list(_recursion(ic, data))
  File "/usr/local/lib/python2.7/dist-packages/pigar/reqs.py", line 51, in _recursion
    ic.visit(parsed)
  File "/usr/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/lib/python2.7/ast.py", line 249, in generic_visit
    self.visit(item)
...
  File "/usr/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/lib/python2.7/ast.py", line 246, in generic_visit
    if isinstance(value, list):
RuntimeError: maximum recursion depth exceeded while calling a Python object

**Comment by Damnever** [comment]
```
pip install git+https://github.com/Damnever/pigar.git@max_recursion_limit --upgrade
```

Hope this can help you.

**Comment by buriy** [comment]
Didn't help:

buriy@bud:~/Projects/wn/wnapi (master)$ pigar
Traceback (most recent call last):
  File "/usr/local/bin/pigar", line 9, in <module>
    load_entry_point('pigar==0.5.4', 'console_scripts', 'pigar')()
  File "/usr/local/lib/python2.7/dist-packages/pigar/__main__.py", line 32, in main
    generate_reqs(save_path, project_path)
  File "/usr/local/lib/python2.7/dist-packages/pigar/__main__.py", line 93, in generate_reqs
    reqs, guess = extract_reqs(project_path)
  File "/usr/local/lib/python2.7/dist-packages/pigar/__main__.py", line 136, in extract_reqs
    modules, local_mods = project_import_modules(path)
  File "/usr/local/lib/python2.7/dist-packages/pigar/reqs.py", line 38, in project_import_modules
    modules.extend(file_import_modules(f.read()))
  File "/usr/local/lib/python2.7/dist-packages/pigar/reqs.py", line 55, in file_import_modules
    ic.visit(parsed)
  File "/usr/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/lib/python2.7/ast.py", line 249, in generic_visit
    self.visit(item)
  File "/usr/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/lib/python2.7/ast.py", line 251, in generic_visit
    self.visit(value)
  File "/usr/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
...
  File "/usr/lib/python2.7/ast.py", line 251, in generic_visit
    self.visit(value)
  File "/usr/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/usr/lib/python2.7/ast.py", line 245, in generic_visit
    for field, value in iter_fields(node):
RuntimeError: maximum recursion depth exceeded

**Comment by Damnever** [comment]
Try this again:
```
pip install git+https://github.com/Damnever/pigar.git@max_recursion_limit --upgrade
```

If still won't help. You can use `pigar -l info` to see which file cause this error, and post the file content.

**Comment by buriy** [comment]
...
13:38:58 Extracting file: /home/buriy/Projects/myproject/.env/lib/python2.7/site-packages/idna/idnadata.py
Traceback (most recent call last):
  File "/usr/local/bin/pigar", line 9, in <module>
    load_entry_point('pigar==0.5.4', 'console_scripts', 'pigar')()
  File "/usr/local/bin/pigar", line 9, in <module>
    load_entry_point('pigar==0.5.4', 'console_scripts', 'pigar')()
  File "/usr/local/lib/python2.7/dist-packages/pigar/__main__.py", line 32, in main
    generate_reqs(save_path, project_path)
  File "/usr/local/lib/python2.7/dist-packages/pigar/__main__.py", line 93, in generate_reqs
    reqs, guess = extract_reqs(project_path)
  File "/usr/local/lib/python2.7/dist-packages/pigar/__main__.py", line 136, in extract_reqs
    modules, local_mods = project_import_modules(path)
  File "/usr/local/lib/python2.7/dist-packages/pigar/reqs.py", line 38, in project_import_modules
    modules.extend(file_import_modules(f.read()))
  File "/usr/local/lib/python2.7/dist-packages/pigar/reqs.py", line 55, in file_import_modules
    ic.visit(parsed)
  File "/usr/local/lib/python2.7/dist-packages/pigar/reqs.py", line 134, in visit
...
  File "/usr/local/lib/python2.7/dist-packages/pigar/reqs.py", line 134, in visit
    return visitor(node)
  File "/usr/lib/python2.7/ast.py", line 245, in generic_visit
    for field, value in iter_fields(node):
RuntimeError: maximum recursion depth exceeded

**Comment by Damnever** [comment]
Ok!
```
pip install git+https://github.com/Damnever/pigar.git@max_recursion_limit --upgrade
```
