### ISSUE TITLE
Pigar requiring user permission

### ISSUE THREAD

**Issue by dhelbegor** [damnever/pigar#50]
I'm trying to use pigar in a personal project, but i'm getting this strange error and I don't now why, can someone help me with that?

environement:
virtualenvwrapper==latest
os ubuntu=latest
pigar 0.9.0

`Traceback (most recent call last):
  File "/home/adailtonnascimento/.local/bin/pigar", line 11, in <module>
    sys.exit(main())
  File "/home/adailtonnascimento/.local/lib/python2.7/site-packages/pigar/__main__.py", line 261, in main
    Main()
  File "/home/adailtonnascimento/.local/lib/python2.7/site-packages/pigar/__main__.py", line 35, in __init__
    self.generate_reqs(save_path, project_path, ignores)
  File "/home/adailtonnascimento/.local/lib/python2.7/site-packages/pigar/__main__.py", line 101, in generate_reqs
    gr = GenerateReqs(save_path, check_path, ignores, self.installed_pkgs)
  File "/home/adailtonnascimento/.local/lib/python2.7/site-packages/pigar/__main__.py", line 41, in installed_pkgs
    self._installed_pkgs = get_installed_pkgs_detail()
  File "/home/adailtonnascimento/.local/lib/python2.7/site-packages/pigar/reqs.py", line 300, in get_installed_pkgs_detail
    mapping.update(_search_path(path))
  File "/home/adailtonnascimento/.local/lib/python2.7/site-packages/pigar/reqs.py", line 339, in _search_path
    info_dir = [_file for _file in os.listdir(dev_dir)
OSError: [Errno 13] Permission denied: '/root/src/polls'`

**Comment by dhelbegor** [comment]
I forget to start my virtualenvenv sorry.
