### ISSUE TITLE
pigar --update processing stops

### ISSUE THREAD

**Issue by IVIuho** [damnever/pigar#56]
Starting update database ...
The process will take a long time!!!
Traceback (most recent call last):
  File "d:\python36\lib\runpy.py", line 193, in _run_module_as_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "d:\python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "d:\python36\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
    "__main__", mod_spec)
  File "d:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python36\Scripts\pigar.exe\__main__.py", line 9, in <module>
  File "d:\python36\lib\site-packages\pigar\__main__.py", line 261, in main
    Main()
  File "d:\python36\lib\site-packages\pigar\__main__.py", line 29, in __init__
    self.update_db()
  File "d:\python36\lib\site-packages\pigar\__main__.py", line 46, in update_db
    update_db()
  File "d:\python36\lib\site-packages\pigar\pypi.py", line 81, in update_db
    updater.run()
  File "d:\python36\lib\site-packages\pigar\pypi.py", line 138, in run
    proc.start()
  File "d:\python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "d:\python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "d:\python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "d:\python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "d:\python36\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.lock objects

I am using pigar 0.9.0

**Comment by lou1306** [comment]
I can reproduce this error with pigar 1.0.0, on macOS Monterey with Python 3.10.4.

**Comment by damnever** [comment]
pigar v2 `pip install pigar==2.0.0` may have fixed this issue.

Feel free to reopen this 🚀
