### ISSUE TITLE
PyPI 404

### ISSUE THREAD

**Issue by wilfredcho** [damnever/pigar#57]
Traceback (most recent call last):
  File "/usr/local/bin/pigar", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/pigar/__main__.py", line 270, in main
    Main()
  File "/usr/local/lib/python3.6/site-packages/pigar/__main__.py", line 37, in __init__
    ignores, comparison_operator)
  File "/usr/local/lib/python3.6/site-packages/pigar/__main__.py", line 108, in generate_reqs
    gr.generate_reqs()
  File "/usr/local/lib/python3.6/site-packages/pigar/__main__.py", line 156, in generate_reqs
    latest = check_latest_version(pkg)
  File "/usr/local/lib/python3.6/site-packages/pigar/pypi.py", line 65, in check_latest_version
    return Downloader().download_package(package).version()
  File "/usr/local/lib/python3.6/site-packages/pigar/pypi.py", line 245, in download_package
    pkg_info = self.download(PKG_INFO_URL.format(name))
  File "/usr/local/lib/python3.6/site-packages/pigar/pypi.py", line 229, in download
    resp.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/pypi/ftl-base/json/

Perhaps there was a change in the url?

**Comment by damnever** [comment]
What did you do? Could you provide more information, such as environment, etc.

There is no project named `ftl-base`: https://pypi.org/search/?q=ftl-base

**Comment by wilfredcho** [comment]
I entered `y` on "Try to search PyPI for the missing modules and filter some unnecessary modules?"
`N` option generated the file.

I think I misread the error as pigar failing. I was expecting it would not throw an error and exit the program. I will close it.
