### ISSUE TITLE
pigar command with y (for yes) stopped working

### ISSUE THREAD

**Issue by peratik** [damnever/pigar#61]
> Some of them may not install in local environment.
> Try to search PyPI for the missing modules and filter some unnecessary modules? (y/[N]) y
> Checking modules on the PyPI...

```
Traceback (most recent call last):
  File "/mnt/d/ISC/bin/pigar", line 8, in <module>
    sys.exit(main())
  File "/mnt/d/ISC/lib/python3.6/site-packages/pigar/__main__.py", line 270, in main
    Main()
  File "/mnt/d/ISC/lib/python3.6/site-packages/pigar/__main__.py", line 37, in __init__
    ignores, comparison_operator)
  File "/mnt/d/ISC/lib/python3.6/site-packages/pigar/__main__.py", line 108, in generate_reqs
    gr.generate_reqs()
  File "/mnt/d/ISC/lib/python3.6/site-packages/pigar/__main__.py", line 156, in generate_reqs
    latest = check_latest_version(pkg)
  File "/mnt/d/ISC/lib/python3.6/site-packages/pigar/pypi.py", line 65, in check_latest_version
    return Downloader().download_package(package).version()
  File "/mnt/d/ISC/lib/python3.6/site-packages/pigar/pypi.py", line 245, in download_package
    pkg_info = self.download(PKG_INFO_URL.format(name))
  File "/mnt/d/ISC/lib/python3.6/site-packages/pigar/pypi.py", line 229, in download
    resp.raise_for_status()
  File "/mnt/d/ISC/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/pypi/anoncreds-rc/json/
```

**Comment by damnever** [comment]
Is this a local package? Could you provide a minimal environment to reproduce it?
