### ISSUE TITLE
pigar -c [PATH] uses current directory instead of PATH

### ISSUE THREAD

**Issue by bganglia** [damnever/pigar#63]
For example, if I want to check the packages of my pigar fork (~/pigar) using
```
cd ~ 
pigar -c pigar/
```
I see the following output:
```
(envname) username@pcname:~$ pigar -c pigar/
Starting check requirements latest version ...
Searching file in "/home/username/pigar" ...
Traceback (most recent call last):
  File "/home/username/miniconda3/envs/envname/bin/pigar", line 11, in <module>
    load_entry_point('pigar', 'console_scripts', 'pigar')()
  File "/home/username/pigar/pigar/__main__.py", line 270, in main
    Main()
  File "/home/username/pigar/pigar/__main__.py", line 32, in __init__
    check_path, ignores, comparison_operator)
  File "/home/username/pigar/pigar/__main__.py", line 86, in check_reqs_latest_version
    reqs.update(parse_reqs(fpath))
  File "/home/username/pigar/pigar/utils.py", line 87, in parse_reqs
    with open(fpath, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/py3_requirements.txt'
```
The file is in ~/pigar, but the code expects it to be in ~, the directory where the command was run.

I can work on this issue.

**Comment by damnever** [comment]
Good catch!

The current logic seems to be a little buggy, PRs are welcome!
