### ISSUE TITLE
maybe symlink should not be followed or just add an option for that?

### ISSUE THREAD

**Issue by Ps7ch3** [damnever/pigar#89]
```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/bin/pigar", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/pigar/__main__.py", line 167, in main
    RequirementsGenerator(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/pigar/core.py", line 65, in generate
    packages, guess = parse_packages(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/pigar/core.py", line 306, in parse_packages
    imported_modules, user_modules = parse_imports(package_root, ignores)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/pigar/parser.py", line 50, in parse_imports
    code = _read_code(fpath)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/pigar/parser.py", line 67, in _read_code
    with open(fpath, 'rb') as f:
OSError: [Errno 62] Too many levels of symbolic links: <some-file-path>
```

**Comment by Ps7ch3** [comment]
```
$ pigar -v
pigar 0.10.0
```
